### ISSUE TITLE
Cannot setup dev environment

### ISSUE THREAD

**Issue by bezin** [cocopon/tweakpane#462]
Hi there, 

I just wanted to contribute to tweakpane, I cannot get the dev environment to work. 

I run `npm install` and npm complains, that it cannot find a version of tweakpane/core. I selected the most recent one. 

After that I run `npm run setup` and `setup:core` fails with the following error message:
```bash 
71 verbose stack TypeError: Cannot set properties of null (setting 'dev')
71 verbose stack     at calcDepFlagsStep (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:34:21)
71 verbose stack     at visit (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:12:20)
71 verbose stack     at visitNode (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
71 verbose stack     at next (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
71 verbose stack     at depth (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
71 verbose stack     at depth (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
71 verbose stack     at calcDepFlags (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:10:15)
71 verbose stack     at Arborist.[copyIdealToActual] (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:1507:7)
71 verbose stack     at Arborist.reify (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:158:35)
71 verbose stack     at async Install.exec (/home/benedict/.nvm/versions/node/v16.17.1/lib/node_modules/npm/lib/commands/install.js:145:5)
```

I tried it with Node 16 and 18 (NPM 8). Which version are you using?

Best
Benedict

**Comment by cocopon** [comment]
Thank you for using Tweakpane! Here is the result of my development environment:

```
repository% node -v                                                                                                           [main]
v16.1.0

repository% npm -v                                                                                                            [main]
7.11.2
```

**Comment by cocopon** [comment]
I found an issue that may be related to this problem. It seems to occur with npm workspaces, but I cannot find a solution...:
https://github.com/npm/cli/issues/3847

Anyway I'm glad it went well.
