### ISSUE TITLE
Readonly `point2d`, `point3d`, `point4d` throws an error

### ISSUE THREAD

**Issue by andrenanninga** [cocopon/tweakpane#605]
I'm trying to monitor a vector(3) in my project, but I'm getting errors when setting `readonly: true` in my binding. I don't have much experience with this library yet so possibly I'm just using it wrong...

```js
const pane = new Pane();
const PARAMS = {
  offset: {x: 50, y: 25},
};
pane.addBinding(PARAMS, 'offset', { readonly: true });
```

```
{
    "message": "No matching controller for 'offset'",
    "name": "TpError",
    "stack": "Error: No matching controller for 'offset'\n    at new TpError (https://tweakpane.github.io/docs/assets/tweakpane.js:85:22)\n    at PluginPool.createBinding (https://tweakpane.github.io/docs/assets/tweakpane.js:7290:15)\n    at RackApi.addBinding (https://tweakpane.github.io/docs/assets/tweakpane.js:1694:31)\n    at Pane.addBinding (https://tweakpane.github.io/docs/assets/tweakpane.js:2210:30)\n    at <anonymous>:4:6",
    "type": "nomatchingcontroller"
}
```

**Comment by lolik9l** [comment]
I have the same problem...

**Comment by cocopon** [comment]
I have not yet implemented 2D/3D point monitoring because I was unsure about the demand for them.

**Comment by lolik9l** [comment]
It would be cool to have it work, so for example I would like to use this to output the actual position of a 3D model (vector3) in my scene.
This will definitely be helpful :)

**Comment by nickdandakis** [comment]
Same issue here, wanted to monitor position of a game entity.

As a workaround, I'm just reading/writing to a string and performing some formatting before the write

```

```
